name: e2e

on:
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-run-example:
    runs-on: [ "self-hosted", "azure-cvm", "ubuntu-2204" ]
    steps:
    - uses: actions/checkout@v3

    - uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential libtss2-dev pkg-config

    - name: Build example project
      working-directory: ./az-snp-vtpm
      run: cargo build --release -p example

    - name: Run example project
      working-directory: ./az-snp-vtpm
      run: sudo ./target/release/example
