name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  az-snp-vtpm:
    runs-on: ubuntu-latest

    steps:
    - name: Install deps
      run: sudo apt-get update && sudo apt-get install -y libtss2-dev

    - uses: actions/checkout@v3

    - uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
        override: true

    - name: Install additional components
      shell: bash
      run: |
        rustup component add rustfmt
        rustup component add clippy

    - name: Build
      run: cargo build --verbose --all
      working-directory: az-snp-vtpm

    - name: Check verifier-only
      run: cargo check --verbose --no-default-features --features=verifier
      working-directory: az-snp-vtpm

    - name: Check attester-only
      run: cargo check --verbose --no-default-features --features=attester
      working-directory: az-snp-vtpm

    - name: Run tests
      run: cargo test --verbose --all
      working-directory: az-snp-vtpm

    - name: Format
      run: cargo fmt --all -- --check
      working-directory: az-snp-vtpm

    - name: Lint
      run: cargo clippy --all-targets --all-features --all -- -D warnings
      working-directory: az-snp-vtpm

  az-report-ready:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
        override: true

    - name: Install additional components
      shell: bash
      run: |
        rustup component add rustfmt
        rustup component add clippy

    - name: Build
      run: cargo build --verbose --all
      working-directory: az-report-ready

    - name: Run tests
      run: cargo test --verbose --all
      working-directory: az-report-ready

    - name: Format
      run: cargo fmt --all -- --check
      working-directory: az-report-ready

    - name: Lint
      run: cargo clippy --all-targets --all-features --all -- -D warnings
      working-directory: az-report-ready
