name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Install deps
      run: sudo apt-get update && sudo apt-get install -y libtss2-dev

    - uses: actions/checkout@v3

    - uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
        override: true

    - name: Install additional components
      shell: bash
      run: |
        rustup component add rustfmt
        rustup component add clippy

    - name: Build
      run: cargo build --verbose
      working-directory: vtpm-snp

    - name: Run tests
      run: cargo test --verbose
      working-directory: vtpm-snp

    - name: Format
      run: cargo fmt --all -- --check
      working-directory: vtpm-snp

    - name: Lint
      run: cargo clippy --all-targets --all-features -- -D warnings
      working-directory: vtpm-snp
