name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: az-cvm-vtpm

    steps:
    - uses: actions/checkout@v3

    - name: Install deps
      run: sudo apt-get update && sudo apt-get install -y libtss2-dev

    - uses: actions-rust-lang/setup-rust-toolchain@v1
      with:
        toolchain: stable
        components: rustfmt, clippy
        override: true

    - name: Build
      run: cargo build --all

    - name: Check verifier-only
      run: cargo check --no-default-features --features=verifier

    - name: Check attester-only
      run: cargo check --no-default-features --features=attester

    - name: Run tests
      run: cargo test --all

    - name: Compile integration tests
      run: cargo test --all --features integration_test --no-run

    - name: Format
      run: cargo fmt --all -- --check

    - name: Lint
      run: cargo clippy --all-targets --all-features --all -- -D warnings
