name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: az-cvm-vtpm

    steps:
    - uses: actions/checkout@v3

    - name: Install deps
      run: sudo apt-get update && sudo apt-get install -y libtss2-dev

    - uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
        override: true

    - name: Install additional components
      shell: bash
      run: |
        rustup component add rustfmt
        rustup component add clippy

    - name: Build
      run: cargo build --verbose --all

    - name: Check verifier-only
      run: cargo check --verbose --no-default-features --features=verifier

    - name: Check attester-only
      run: cargo check --verbose --no-default-features --features=attester

    - name: Run tests
      run: cargo test --verbose --all

    - name: Format
      run: cargo fmt --all -- --check

    - name: Lint
      run: cargo clippy --all-targets --all-features --all -- -D warnings
