name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Install deps
      run: sudo apt-get update && sudo apt-get install -y libtss2-dev

    - uses: actions/checkout@v3

    - name: Build
      run: cargo build --verbose
      working-directory: vtpm-snp-report

    - name: Run tests
      run: cargo test --verbose
      working-directory: vtpm-snp-report
